pluginManagement {
    repositories {
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/geckour/Q")

            credentials {
                username = getKey('gpr.usr', settingsDir) ?: System.getenv('GPR_USER')
                password = getKey('gpr.key', settingsDir) ?: System.getenv('GPR_TOKEN')
            }

            content {
                includeModule('androidx.media3', 'media3-decoder-ffmpeg')
            }
        }
    }
}

static def getKey(keyName, File settingsDir) {
    Properties props = new Properties()
    props.load(new FileInputStream(new File(settingsDir, "secret.properties")))
    return props[keyName]
}

include ':app'